### ISSUE TITLE
crashes after clicking on the channel 

### ISSUE THREAD

**Issue by leow1e** [5punk/react-slack-chat#42]
_Please fill only what you can_

**crashes after clicking on the channel **
Before clicking on the chat box, on the inspector there is this error:

index.js:1 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the t component.

The chat box and channel still appears ok, until clicking on the channel, then it would crash and the chat box will disappear. 
Could you please help me to identify what is wrong?
![image](https://user-images.githubusercontent.com/23429820/88375275-dc864c00-cdcd-11ea-9862-88057c3f9d00.png)

**Comment by 5punk** [comment]
Sorry for thate late reply.
honestly the botname should be unique for every customer / visitor but that's ok.

Can you check your console to see if any errors are visible?

**Comment by sivang7** [comment]
I have the same issue and no errors exists in console

**Comment by michele6000** [comment]
@5punk same issue, is due to deprecated methods https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api . will u patch ?

**Comment by sivang7** [comment]
I used this fork that use new API and it works good: https://github.com/jwhiteaei/react-slack-chat-jw

**Comment by 5punk** [comment]
This fork (https://github.com/jwhiteaei/react-slack-chat-jw) uses 2 separate versions of the slack npm library, the upgraded one as well as the outdated one in order to preserve the functionality.

______

I've gone ahead and refactored this library and **fixed** this issue in the process.

Fix merged: https://github.com/5punk/react-slack-chat/pull/43

Fix tested by @vocalists

This new refactor aims to be much more efficient and cost effective in terms of API usage.

Thank you.

**Comment by ustincameron** [comment]
Hi, using latest version. Both network calls show successful with data, but zero console logs even with debugMode. 
Still crashes when clicking on a channel or using the defaultChannel prop.

Any ideas?
